CC=gcc
CFLAGS=-g
EXE=practica2

all:
	$(CC) $(CFLAGS) -o $(EXE) practica2.c
	
run:	all
	./$(EXE) 123$$ +123$$ -123$$ 123.123$$ +123.123$$ -123.123$$ 0x123$$ 0xabc$$ 0x1ab$$ 0xab1$$ 

clean:
	rm $(EXE)
